### ISSUE TITLE
Two mouses appear in the Cobrowsing Window

### ISSUE THREAD

**Issue by Comm100** [Comm100/Cobrowse#15]
![attachfilehandler1](https://user-images.githubusercontent.com/32153205/38978517-3dfb2a48-43ea-11e8-8b13-70275523884e.png)

**Comment by jonmeadglance** [comment]
This is correct, the orange cursor is the agents cursor and the red cursor is the customers.  If you have more than one agent, you may see three if the other agent is moving/gesturing.
