### ISSUE TITLE
Website look quite different from agent view on iPad

### ISSUE THREAD

**Issue by Comm100** [Comm100/Cobrowse#16]
Visitor platform: iPad iOS 11
Website: https://myassignmenthelp.com/Home/order-pay.php?Id=ODI5MjQ4My1xSEticFptbi00MTgwOTk0

Agent View:

![attachfilehandler 3](https://user-images.githubusercontent.com/32153205/38978644-94c20b3a-43ea-11e8-9be6-0dd4cc0c5765.png)

![attachfilehandler 4](https://user-images.githubusercontent.com/32153205/38978678-abe3685e-43ea-11e8-9f1a-cbad65af20f4.png)

![attachfilehandler 7](https://user-images.githubusercontent.com/32153205/38978804-fbb27974-43ea-11e8-8603-2fd80b0c0639.png)

Visitor side:

![attachfilehandler 5](https://user-images.githubusercontent.com/32153205/38978760-e266a6f2-43ea-11e8-908d-7dc856d15869.png)

![attachfilehandler 6](https://user-images.githubusercontent.com/32153205/38978784-ed6304d8-43ea-11e8-9ec1-7a86fb40ce23.png)

![attachfilehandler 8](https://user-images.githubusercontent.com/32153205/38978821-062b5948-43eb-11e8-8d06-7a01efd51ab8.png)

**Comment by jonmeadglance** [comment]
This seems like the assets/resources are not making it to the agent viewer.  Are the websites CSS resources private or do they require an authorization token?  We can host these CSS files on our CDN and deliver them to the agent viewer on session join, but this would make the CSS files public (which shouldn't be too big of a problem, they don't typically have any information).

**Comment by Comm100** [comment]
can not reproduce
