### ISSUE TITLE
The cursor blinks in the Cobrowsing Window and text can be input sometimes.

### ISSUE THREAD

**Issue by Comm100** [Comm100/Cobrowse#21]
On visitor side, the cursor is in the input box.
Once clicked on the page in the Cobrowsing Window, the cursor starts blinking and text can be input.

![attachfilehandler4](https://user-images.githubusercontent.com/32153205/38983771-bf8ee34e-43f7-11e8-9f32-c677e7ef12ee.png)

**Comment by jonmeadglance** [comment]
Does the agent have remote control?  Is this reproducible? We will have to do a bit of investigation on this one.

**Comment by Comm100** [comment]
Does the agent have remote control? -- no
Is this reproducible?  -- not every time, but pretty frequently
