### ISSUE TITLE
Cobrowsing window can not show the images or something else of the visitor.

### ISSUE THREAD

**Issue by Comm100** [Comm100/Cobrowse#8]
![image](https://user-images.githubusercontent.com/32153205/38974874-402213b0-43de-11e8-997f-1845e36fa177.png)

**Comment by jonmeadglance** [comment]
What are these images?  Are they private?  If these are needed on the agent viewer, then they need to be either public or hosted by Glance on our network.  If, however, these are SVG images, they will always be blocked because of CORS policies with regards to SVG images specifically.

**Comment by Comm100** [comment]
duplicate #11
